quarkus.application.name=reviews-service
quarkus.http.port=8083
# gRPC Server
quarkus.grpc.server.port=9083

# OIDC Configuration - ?????? REST API
quarkus.oidc.auth-server-url=http://localhost:8180/realms/quarkus
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=backend-secret
quarkus.oidc.application-type=service

# Bearer token authentication
quarkus.oidc.token.issuer=http://localhost:8180/realms/quarkus

# Security policy - ?????? ???? ??????????
quarkus.http.auth.permission.authenticated.paths=/api/*
quarkus.http.auth.permission.authenticated.policy=authenticated

# Dev Services
quarkus.keycloak.devservices.enabled=true