quarkus.http.port=8080

# OIDC Configuration for DEV mode
quarkus.oidc.auth-server-url=http://localhost:8180/realms/quarkus
quarkus.oidc.client-id=frontend-client
quarkus.oidc.credentials.secret=secret
quarkus.oidc.application-type=web-app

# OIDC paths
quarkus.oidc.authentication.redirect-path=/
quarkus.oidc.authentication.restore-path-after-redirect=true

# Dev Services - Keycloak ???? ??????????? ????????? ? dev ??????
quarkus.keycloak.devservices.enabled=true
quarkus.keycloak.devservices.realm-path=quarkus-realm.json

# REST Client config
quarkus.rest-client.product-service.url=http://localhost:8082
quarkus.rest-client.order-service.url=http://localhost:8081
quarkus.rest-client.review-service.url=http://localhost:8083

# Security policy
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.http.auth.permission.public.paths=/,/index.html
quarkus.http.auth.permission.public.policy=permit