quarkus.http.port=8080

#oidc config for dev
quarkus.http.auth.permission.all-resources.paths=/*
quarkus.http.auth.permission.all-resources.policy=authenticated
quarkus.oidc.application-type=web_app
quarkus.oidc.logout.path=/logout

#rest client
quarkus.rest-client.product-service.url=http://localhost:8082
quarkus.rest-client.order-service.url=http://localhost:8081
quarkus.rest-client.review-service.url=http://localhost:8083

#security policy
#quarkus.http.auth.permission.public.paths=/,/index.html
#uarkus.http.auth.permission.public.policy=permit
#uarkus.http.auth.permission.authenticated.paths=/home,/products,/orders,/reviews
#uarkus.http.auth.permission.authenticated.policy=authenticated

#logging
quarkus.log.category."io.quarkus.oidc".level=DEBUG