quarkus.application.name=order-service
quarkus.http.port=8081

# REST Client
quarkus.rest-client.product-service.url=http://localhost:8082

# gRPC Client
quarkus.grpc.clients.product-service.host=localhost
quarkus.grpc.clients.product-service.port=9082

# gRPC Server
quarkus.grpc.server.port=9081