quarkus.application.name=order-service
quarkus.http.port=8081

#postgre db config
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/orders_db

## RabbitMQ Configuration
#rabbitmq-host=localhost
#rabbitmq-port=5672
#rabbitmq-username=guest
#rabbitmq-password=guest

# Incoming channel - Product Events
mp.messaging.incoming.product-events.value.deserializer=io.smallrye.reactive.messaging.rabbitmq.json.JsonObjectMapperDeserializer

mp.messaging.incoming.product-events.connector=smallrye-rabbitmq
mp.messaging.incoming.product-events.queue.name=order-service-product-events
mp.messaging.incoming.product-events.queue.durable=true
mp.messaging.incoming.product-events.exchange.name=product-events-exchange
mp.messaging.incoming.product-events.exchange.type=topic
mp.messaging.incoming.product-events.routing-key=product.#

#rest client
quarkus.rest-client.product-service.url=http://localhost:8082

#gRPC client
quarkus.grpc.clients.product-service.host=localhost
quarkus.grpc.clients.product-service.port=9082

#gRPC server
quarkus.grpc.server.port=9081
quarkus.oidc.application-type=service

#security policy
quarkus.http.auth.permission.authenticated.paths=/api/*
quarkus.http.auth.permission.authenticated.policy=authenticated

#prod oidc config
%prod.quarkus.oidc.auth-server-url=http://localhost:8180/realms/jewelry-store
%prod.quarkus.oidc.client-id=backend-service
%prod.quarkus.oidc.credentials.secret=backend-secret
%prod.quarkus.oidc.application-type=service

#token validation
%prod.quarkus.oidc.token.issuer=http://localhost:8180/realms/jewelry-store

#security
%prod.quarkus.http.auth.permission.authenticated.paths=/api/*
%prod.quarkus.http.auth.permission.authenticated.policy=authenticated