quarkus.application.name=order-service
quarkus.http.port=8081

#rest client
quarkus.rest-client.product-service.url=http://localhost:8082

#gRPC client
quarkus.grpc.clients.product-service.host=localhost
quarkus.grpc.clients.product-service.port=9082

#gRPC server
quarkus.grpc.server.port=9081
quarkus.oidc.application-type=service

#security policy
quarkus.http.auth.permission.authenticated.paths=/api/*
quarkus.http.auth.permission.authenticated.policy=authenticated

#prod oidc config
%prod.quarkus.oidc.auth-server-url=http://localhost:8180/realms/jewelry-store
%prod.quarkus.oidc.client-id=backend-service
%prod.quarkus.oidc.credentials.secret=backend-secret
%prod.quarkus.oidc.application-type=service

#token validation
%prod.quarkus.oidc.token.issuer=http://localhost:8180/realms/jewelry-store

#security
%prod.quarkus.http.auth.permission.authenticated.paths=/api/*
%prod.quarkus.http.auth.permission.authenticated.policy=authenticated