quarkus.application.name=product-service
quarkus.http.port=8082

#rest client
quarkus.rest-client.review-service.url=http://localhost:8083

#gRPC server
quarkus.grpc.server.port=9082

#oidc config ?????? rest api
quarkus.oidc.auth-server-url=http://localhost:8180/realms/quarkus
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=backend-secret
quarkus.oidc.application-type=service

#bearer token authentication
quarkus.oidc.token.issuer=http://localhost:8180/realms/quarkus

#security policy
quarkus.http.auth.permission.authenticated.paths=/api/*
quarkus.http.auth.permission.authenticated.policy=authenticated

#prod oidc config
%prod.quarkus.oidc.auth-server-url=http://localhost:8180/realms/jewelry-store
%prod.quarkus.oidc.client-id=backend-service
%prod.quarkus.oidc.credentials.secret=backend-secret
%prod.quarkus.oidc.application-type=service

#token validation
%prod.quarkus.oidc.token.issuer=http://localhost:8180/realms/jewelry-store

#security
%prod.quarkus.http.auth.permission.authenticated.paths=/api/*
%prod.quarkus.http.auth.permission.authenticated.policy=authenticated