syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.yaloys.products.grpc.product";

package product;

service ProductService {
  rpc GetProduct(ProductRequest) returns (ProductResponse);
  rpc GetProducts(ProductsRequest) returns (ProductsResponse);
}

message ProductRequest {
  int32 id = 1;
}

message ProductsRequest {
  repeated int32 ids = 1;
}

message ProductResponse {
  int32 id = 1;
  string name = 2;
  string price = 3;
}

message ProductsResponse {
  repeated ProductResponse products = 1;
}